In [ ]:
import pandas as pd
import numpy as np

In [ ]:
#creating dataset
from sklearn.datasets import make_classification
X,y = make_classification(n_samples=1000,n_features=10,n_informative=3,n_classes=3,random_state = 60)

In [ ]:
y     #it shows 3 types of outputs

array([1, 1, 2, 0, 0, 0, 2, 2, 0, 0, 2, 0, 2, 0, 2, 1, 1, 0, 0, 1, 1, 0,
       2, 2, 2, 0, 2, 2, 0, 0, 2, 0, 2, 2, 2, 2, 2, 1, 2, 0, 1, 2, 0, 2,
       2, 1, 2, 2, 0, 2, 1, 1, 1, 2, 2, 0, 1, 0, 2, 0, 1, 1, 1, 0, 2, 2,
       0, 0, 2, 2, 0, 0, 2, 1, 0, 1, 1, 0, 2, 1, 0, 0, 2, 1, 1, 0, 2, 1,
       2, 2, 2, 0, 0, 2, 2, 2, 1, 2, 1, 1, 0, 1, 1, 2, 2, 0, 1, 0, 0, 2,
       0, 2, 0, 2, 1, 1, 1, 0, 2, 0, 2, 1, 2, 1, 2, 1, 1, 1, 0, 2, 2, 0,
       1, 1, 1, 0, 2, 1, 2, 0, 1, 2, 0, 1, 1, 0, 2, 2, 2, 0, 2, 2, 1, 0,
       1, 2, 0, 2, 2, 2, 0, 2, 2, 1, 0, 2, 1, 0, 0, 0, 1, 1, 1, 1, 2, 0,
       0, 1, 0, 1, 1, 2, 2, 1, 1, 0, 0, 0, 2, 2, 0, 1, 2, 2, 2, 1, 2, 2,
       2, 2, 1, 0, 0, 1, 0, 0, 2, 0, 0, 2, 1, 2, 2, 0, 2, 1, 1, 1, 0, 2,
       0, 1, 2, 0, 0, 2, 0, 2, 2, 2, 0, 2, 2, 0, 0, 0, 0, 0, 1, 2, 0, 2,
       0, 0, 2, 1, 0, 2, 1, 0, 2, 1, 2, 0, 1, 0, 1, 1, 1, 1, 2, 0, 2, 2,
       1, 1, 0, 0, 2, 2, 2, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 2, 2, 1,
       0, 2, 0, 2, 2, 0, 1, 2, 2, 1, 0, 0, 2, 2, 1,

In [ ]:
#train test split

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=42)

In [ ]:
#training
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(multi_class='ovr')
#ovr=One versus Rest
classifier.fit(X_train,y_train)
y_pred = classifier.predict(X_test)

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(


In [ ]:
#Performance metrics

from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
score = accuracy_score(y_test,y_pred)
print("Accuracy=",score)
print('Classification Report:')
print(classification_report(y_test,y_pred))
print('Confusion Matrix:')
print(confusion_matrix(y_test,y_pred))

Accuracy= 0.8466666666666667
Classification Report:
              precision    recall  f1-score   support

           0       0.77      0.89      0.83        96
           1       0.93      0.87      0.90        91
           2       0.86      0.80      0.83       113

    accuracy                           0.85       300
   macro avg       0.85      0.85      0.85       300
weighted avg       0.85      0.85      0.85       300

Confusion Matrix:
[[85  5  6]
 [ 3 79  9]
 [22  1 90]]


##HyperParameter Tuning

1.Grid SearchCV

In [ ]:
model = LogisticRegression()
c_values = [100,10,1.0,0.1,0.01]
max_iters = [100, 200, 500, 1000] # Good to tune this for convergence
params =[
    {
        'multi_class': ['ovr'], # liblinear only works with 'ovr' for multiclass
        'penalty': ['l1', 'l2'], # liblinear supports L1 and L2
        'C': c_values,
        'solver': ['liblinear'],
        'max_iter': max_iters # Add max_iter
    },
    {
        'multi_class': ['ovr', 'multinomial'], # These solvers can handle both
        'penalty': ['l2'], # lbfgs, newton-cg, sag mainly support L2 (or none)
        'C': c_values,
        'solver': ['lbfgs', 'newton-cg', 'sag'],
        'max_iter': max_iters
    },
    {
        'multi_class': ['ovr', 'multinomial'], # saga can handle both
        'penalty': ['l1', 'l2', 'elasticnet'], # saga is versatile
        'C': c_values,
        'solver': ['saga'],
        'l1_ratio': [0.3, 0.5, 0.7], # Only used if penalty is 'elasticnet'
        'max_iter': max_iters
    }
]

In [ ]:
from sklearn.model_selection import GridSearchCV,StratifiedKFold
cv = StratifiedKFold()
grid = GridSearchCV(estimator=model,param_grid=params,cv=cv,scoring='accuracy')
grid.fit(X_train,y_train)
grid

Streaming output truncated to the last 5000 lines.
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:1196: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:1196: UserWarning: l1_ratio parameter is only used 

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(),
             param_grid=[{'C': [100, 10, 1.0, 0.1, 0.01],
                          'max_iter': [100, 200, 500, 1000],
                          'multi_class': ['ovr'], 'penalty': ['l1', 'l2'],
                          'solver': ['liblinear']},
                         {'C': [100, 10, 1.0, 0.1, 0.01],
                          'max_iter': [100, 200, 500, 1000],
                          'multi_class': ['ovr', 'multinomial'],
                          'penalty': ['l2'],
                          'solver': ['lbfgs', 'newton-cg', 'sag']},
                         {'C': [100, 10, 1.0, 0.1, 0.01],
                          'l1_ratio': [0.3, 0.5, 0.7],
                          'max_iter': [100, 200, 500, 1000],
                          'multi_class': ['ovr', 'multinomial'],
                          'penalty': ['l1', 'l2', 'elasticnet'],
                          'solver': ['saga']}],
             scoring='accuracy')

In [ ]:
grid.best_params_

{'C': 0.1,
 'l1_ratio': 0.3,
 'max_iter': 100,
 'multi_class': 'multinomial',
 'penalty': 'l1',
 'solver': 'saga'}

In [ ]:
grid.best_score_

np.float64(0.8928571428571429)

In [ ]:
y_pred_grid = grid.predict(X_test)      #pred output for grid searchCV
score = accuracy_score(y_test,y_pred_grid)
print("Accuracy=",score)
print('Classification Report:')
print(classification_report(y_test,y_pred_grid))
print('Confusion Matrix:')
print(confusion_matrix(y_test,y_pred_grid))

Accuracy= 0.8633333333333333
Classification Report:
              precision    recall  f1-score   support

           0       0.80      0.90      0.85        96
           1       0.94      0.87      0.90        91
           2       0.86      0.83      0.85       113

    accuracy                           0.86       300
   macro avg       0.87      0.87      0.87       300
weighted avg       0.87      0.86      0.86       300

Confusion Matrix:
[[86  4  6]
 [ 3 79  9]
 [18  1 94]]


###Accuracy increased from 84% to 86%

2.Random SearchCV

In [ ]:
from sklearn.model_selection import RandomizedSearchCV

In [ ]:
model = LogisticRegression()
randomcv = RandomizedSearchCV(estimator=model,param_distributions=params,scoring='accuracy',cv=5,n_jobs=-1)

In [ ]:
randomcv.fit(X_train,y_train)
randomcv

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(


RandomizedSearchCV(cv=5, estimator=LogisticRegression(), n_jobs=-1,
                   param_distributions=[{'C': [100, 10, 1.0, 0.1, 0.01],
                                         'max_iter': [100, 200, 500, 1000],
                                         'multi_class': ['ovr'],
                                         'penalty': ['l1', 'l2'],
                                         'solver': ['liblinear']},
                                        {'C': [100, 10, 1.0, 0.1, 0.01],
                                         'max_iter': [100, 200, 500, 1000],
                                         'multi_class': ['ovr', 'multinomial'],
                                         'penalty': ['l2'],
                                         'solver': ['lbfgs', 'newton-cg',
                                                    'sag']},
                                        {'C': [100, 10, 1.0, 0.1, 0.01],
                                         'l1_ratio': [0.3, 0.5, 0.7],
                                         'max_iter': [100, 200, 500, 1000],
                                         'multi_class': ['ovr', 'multinomial'],
                                         'penalty': ['l1', 'l2', 'elasticnet'],
                                         'solver': ['saga']}],
                   scoring='accuracy')

In [ ]:
randomcv.best_params_

{'solver': 'saga',
 'penalty': 'elasticnet',
 'multi_class': 'multinomial',
 'max_iter': 1000,
 'l1_ratio': 0.5,
 'C': 0.01}

In [ ]:
randomcv.best_score_

np.float64(0.8885714285714286)

In [ ]:
y_pred_random = randomcv.predict(X_test)      #pred output for random searchCV
score = accuracy_score(y_test,y_pred_random)
print("Accuracy=",score)
print('Classification Report:')
print(classification_report(y_test,y_pred_random))
print('Confusion Matrix:')
print(confusion_matrix(y_test,y_pred_random))

Accuracy= 0.8366666666666667
Classification Report:
              precision    recall  f1-score   support

           0       0.75      0.90      0.82        96
           1       0.96      0.84      0.89        91
           2       0.83      0.79      0.81       113

    accuracy                           0.84       300
   macro avg       0.85      0.84      0.84       300
weighted avg       0.85      0.84      0.84       300

Confusion Matrix:
[[86  2  8]
 [ 5 76 10]
 [23  1 89]]


So we find that Grid SearchCV gave better accuracy than Random SearchCV , so it depends from problem to problem and we choose the best one