In [2]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [5]:
import numpy as np

arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [7]:
arr2 = np.array([[1,2,3,4,5]])
arr2.shape # now arr2 is 2D  has 1 row and 5 cols

(1, 5)

In [11]:
arr3 = np.array([[1,2,3,4,5,6]])
arr3.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
arr4 = np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(arr4)
print(arr4.shape)

[[1 2 3 4 5]
 [6 7 8 9 0]]
(2, 5)


In [14]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [15]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
#identity matrix

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
print(arr4.ndim)        #no. of dimensions of arr4
print(arr4.size)        #no. of elements
print(arr4.dtype)       #data type of each item
print(arr4.itemsize)    #Byte size of each item

2
10
int64
8


In [19]:
# Vectorized operations

arr1  = np.array([1,2,3,4,5])
arr2  = np.array([6,7,8,9,2])

# element wise operations
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1//arr2)

[ 7  9 11 13  7]
[-5 -5 -5 -5  3]
[ 6 14 24 36 10]
[0 0 0 0 2]


In [23]:
## universal functions

arr = np.array([1,4,9,16])
print(np.sqrt(arr))
print(np.exp(arr))
print(np.sin(arr))
print(np.log(arr))

[1. 2. 3. 4.]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]
[ 0.84147098 -0.7568025   0.41211849 -0.28790332]
[0.         1.38629436 2.19722458 2.77258872]


In [24]:
# slicing

arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [35]:
print(arr[1][2])
print(arr[1:])

7
[[ 5  6  7  8]
 [ 9 10 11 12]]


In [37]:
print(arr[1:,2:])
print(arr[0:2,2:])

[[ 7  8]
 [11 12]]
[[3 4]
 [7 8]]


In [40]:
# modify elements

arr[0,0] = 0
print(arr)

[[ 0  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [47]:
## Normalization: to have a mean of 0 and standard deviation of 1

data = np.array([1,2,3,4,5])

mean = np.mean(data)
std_dev = np.std(data)

#normalize data
ndata = (data - mean)/std_dev
print(ndata)

print(np.mean(ndata))
print(np.std(ndata))


[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
0.0
0.9999999999999999


In [48]:
median = np.median(data)
print(median)
variance = np.var(data)
print(variance)

3.0
2.0


In [49]:
data = np.array([1,2,3,4,5,6,7,8,9,10])

data<5

array([ True,  True,  True,  True, False, False, False, False, False,
       False])

In [50]:
data[data>5]

array([ 6,  7,  8,  9, 10])

In [53]:
data[(data>0) & (data<6)]

array([1, 2, 3, 4, 5])